### PR TITLE
better ui

### PR DESCRIPTION
**Pull request by BoredSathvik**

### CODE REVIEW

**Comment by quartzexpressDEV** [comment]
i found a few bugs with this:
- the font is slightly bigger on the clear button than it is on the start button
- you cant move the window
will merge this when those bugs are fixed






_is this how prs work ive never done github pls help_

**Comment by tobyrschwartz** [comment]
Yes that’s how it works

**Comment by BoredSathvik** [comment]
> i found a few bugs with this:
> 
> * the font is slightly bigger on the clear button than it is on the start button
> * you cant move the window
>   will merge this when those bugs are fixed
> 
> _is this how prs work ive never done github pls help_

i made font slightly bigger for more readablity

**Comment by BoredSathvik** [comment]
@Technosword can you give us the new texture pack non encrypted 🥺

**Pull request merged**
